clone_depth: 256

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  PYPI_PWD:
    secure: u3JJYpvKB9aFJvpURLRKIol/Y5IdKVZQ5gNZ2jefc0RC67Jeq3yBgVTTcTSSV4tm
  PYPI_USR: ci_zmdd
  R_VERSION: 3.6.3
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

install:
  # actual install
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # Check that we have the expected version and architecture for Python
  - python --version
  # Install R
  - choco install -y wget --version 1.20
  - wget -q https://cran.r-project.org/bin/windows/base/old/%R_VERSION%/R-%R_VERSION%-win.exe
  - R-%R_VERSION%-win.exe /SILENT /DIR="C:\\Users\\appveyor\\R"
  - set R_HOME=C:\Users\appveyor\R
  - set PATH=%PATH%;C:\Users\appveyor\R\bin\x64
  - set PATH=%PATH%;C:\Users\appveyor\R\bin\i386
  - set RPY2_CFFI_MODE="ABI"
  - appveyor R -e "install.packages('lme4', repos='http://cran.r-project.org')"
  - echo %PATH%
  # upgrade pip
  - appveyor-retry python -m pip install --upgrade pip wheel
  # latest version of fcswrite
  - appveyor-retry pip install git+git://github.com/ZELLMECHANIK-DRESDEN/fcswrite.git --no-deps
  # the rest
  - appveyor-retry pip install -e .[all]
  - python -m pip freeze
  # verify R installation
  - python -c "from rpy2 import situation; [print(ss) for ss in situation.iter_info()]"

build: off

test_script:
  - appveyor-retry pip install pytest
  - appveyor-retry pip install coverage
  - appveyor-retry pip install codecov
  - coverage run --source=dclab -m pytest tests
  - coverage report -m
  # Allow codecov to fail
  - codecov || exit 0

after_test:
  - appveyor-retry pip install twine wheel
  # If tests are successful, create a whl package for the project.
  - python setup.py bdist_wheel
  - python setup.py sdist
  # setup PyPI credentials
  - cmd: "echo [pypi] > %USERPROFILE%\\.pypirc"
  - cmd: "echo username: %PYPI_USR% >> %USERPROFILE%\\.pypirc"
  - cmd: "echo password: %PYPI_PWD% >> %USERPROFILE%\\.pypirc"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

on_success:
  - cmd: "if [%APPVEYOR_REPO_TAG%]==[true] twine upload --skip-existing dist\\*.whl"
  - cmd: "if [%APPVEYOR_REPO_TAG%]==[true] twine upload --skip-existing dist\\*.tar.gz"
