version: 2
formats:
 - pdf
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - RPY2_CFFI_MODE=ABI
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
